name: codingMobs
author: codingPotato
main: com.egirlsnation.codingMobs.Main
version: 0.0.1
api-version: 1.17
website: 
dev-url: 
load: STARTUP

commands:
   debug:
      description: different debug commands.
      usage: /<command>
      permissions: 
      
   spawn:
      description: spawns a custom entity on your location.
      usage: /<command>
      permissions: 